- name: frontend
  projectFile: FrontEnd/FrontEnd.csproj
- name: backend
  projectFile: BackEnd/BackEnd.csproj
- name: rabbit
  dockerImage: rabbitmq
  bindings:
    - name: default
      address: tcp://localhost:5672
      protocol: rabbitmq
- name: worker
  projectFile: Worker/Worker.csproj
- name: redis
  dockerImage: redis
  bindings:
    - name: default
      address: tcp://localhost:6379
      protocol: redis
