- name: frontend
  project: FrontEnd/FrontEnd.csproj
  bindings:
    - port: 7000
- name: backend
  project: BackEnd/BackEnd.csproj
  replicas: 2
  bindings:
    - port: 8000
- name: worker
  project: Worker/Worker.csproj
- name: rabbit
  dockerImage: rabbitmq
  bindings:
    - port: 5672
      protocol: rabbitmq
- name: redis
  dockerImage: redis
  bindings:
    - port: 6379
      protocol: redis